### ISSUE TITLE
Update readme with more example

### ISSUE THREAD

**Issue by ArcaneDiver** [easybotics/node-rpi-rgb-led-matrix#2]
Pls may you add example for scroll some text or display and image? I'm not really skillful the a help will be more appreciated.
Thanks.

**Comment by keptan** [comment]
So if you're really having trouble you could use our node-red library here: https://github.com/easybotics/node-red-contrib-easybotics-led-matrix

for your specific example it probably looks something like this

```
var Matrix = require("easybotics-rgb-led-matrix");
led = new Matrix(32, 64, 1, 1, 100, "regular"); //this might be different for you
 
const input = "hello world!"; //whever you get the input from
const font  =  __dirname + '/fonts/' + "5x8.bdf";
 
//should be a function that calculates the postition based on timestamp
//and increments the x position
var x = 0;
var y = 0;
 
led.drawText(x, y, 255, 255, 255, input, font);
led.update();
while(true){};

```
