### ISSUE TITLE
matrix.update never returns or displays on Pi 4

### ISSUE THREAD

**Issue by riney** [easybotics/node-rpi-rgb-led-matrix#8]
Hi! I put the sample code under "Get some fun" into a file, and invoked it with `sudo node display.js`. The call to `matrix.update()` never returns, and nothing is shown on the display. I'm using Node 10.16.2 under Raspbian Lite on a Raspberry Pi 4. For interfacing, I'm using one of `hzeller`'s active 3-chain boards. The displays are 32x64 P3 panels, with the FM6126 chipset. Using `hzeller`'s library directly works. Any thoughts?

**Comment by ArcaneDiver** [comment]
May you send the code?

**Comment by riney** [comment]
@ArcaneDiver Well, I was worried about that too, but as I said, the native library underlying `node-rpi-rgb-led-matrix` works, so I'm not thinking it's a PI4 issue. I will test with a Pi 3 though, just to make sure.

**Comment by riney** [comment]
Welp, that's what I get for assuming. I moved the interface board over to a Pi 3 B+ and it works like a champ. Well, if there's anything I can do to help test on Pi 4, I've got three of 'em not doing anything :)

**Comment by clowrey** [comment]
Yup we have not tested anything yet on any hardware but the pi 3B+ - if you want to debug on your own and find out what's not working feel free. We will eventually update it to work on the pi4 but it's not a priority at the moment.

**Comment by keptan** [comment]
It's possible you could pull this git-repo, update hzellers sub-repo to the newer one and rebuild to get it to work on rpi4. I've seen some discussion about the hardware on his repo.

**Comment by clowrey** [comment]
We have just updated this to work on RPI4 ! test it if you can :)
